### PR TITLE
Fix expression ignoring

### LINKED ISSUE #72: @{{ }} not working as expected
Noticed two issues with [using @{{ }} for ignoring expressions](https://github.com/posthtml/posthtml-expressions#ignoring-expressions).

### Escaping fails inside attributes

This:

```html
<a href="@{{ foo }}">Home</a>
```

Becomes this:

```html
<a href="@{{ undefined }}">Home</a>
```

It still tries to evaluate the expression when inside an attribute.

### Escaping in content is a bit glitchy

```html
<p>This is some @{{ variable }}, and here is another: @{{ bar }}</p>
```

Becomes:

```html
<p>This is some {{ variable }}, and here is another: @{{ bar }}</p>
```

Basically, since the node is returned right when `@` is encountered, any subsequent escaped expressions will be returned as-is (including the `@` symbol).

So it's actually enough to do:

```html
<p>This is some @{{ variable }}, and here is another: {{ bar }}</p>
```

... and that will output:

```html
<p>This is some {{ variable }}, and here is another: {{ bar }}</p>
```

However, this isn't expected behavior.

### PR DESCRIPTION
**Pull request by cossssmin**
This PR fixes a couple of bugs when ignoring expressions with `@{{ }}`, as described in #72.

Subsequent ignored expressions now properly work in text nodes:

```html
<p>Here's one @{{ variable }} and here's @{{ another }}.</p>
```

Result:

```html
<p>Here's one {{ variable }} and here's {{ another }}.</p>
```

Expressions are now also ignored inside attribute values:

```html
<p data-foo="@{{ bar }}">Lorem ipsum.</p>
```

Result:

```html
<p data-foo="{{ bar }}">Lorem ipsum.</p>
```

When merged, this PR will close #72.

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -174,15 +174,16 @@ function walk (opts, nodes) {
       return m
     }
 
+    const ignoredBefore = delimitersSettings[1].text[0]
+    const ignoredAfter = delimitersSettings[1].text[1]
+    const toReplace = new RegExp(`@${ignoredBefore}`, 'g')
+    let ignoredExpression = new RegExp(`@${ignoredBefore}(.+?)${ignoredAfter}`, 'g')
```
Comment (Scrum) [inline lib/index.js:180]: I think it’s better to put on line 154

`ignoredExpression` I think it's worth renaming to `ignoredNodeExpression`

File: lib/index.js [hunk 2]
```diff
@@ -198,8 +199,14 @@ function walk (opts, nodes) {
 
     // if not, we have an object, so we need to run the attributes and contents
     if (node.attrs) {
+      // adapt regex to work with attribute values
+      ignoredExpression = new RegExp(`.*@${ignoredBefore}(.+?)${ignoredAfter}`)
```
Comment (Scrum) [inline lib/index.js:203]: I think it’s better to put on line 154

`ignoredExpression` I think it's worth renaming to `ignoredAttrsExpression`

**Comment by Scrum** [comment]
@cossssmin Hi, why didn’t you move it to line 154? after all, during the round-trip, regular degeneration with `ignore`

**Comment by cossssmin** [comment]
Rushed to push the fix, sorry about that - doing it now... 🤦‍♂️

**Comment by Scrum** [comment]
Don't worry about it

**Comment by cossssmin** [comment]
Wait, it won't work there, `delimitersSettings` isn't yet defined... did you mean line 164?

**Comment by Scrum** [comment]
Yes, I was a little mistaken, but I would like to endure them or iterate `walk`, but I see for this they need to be taken out of the osprey for visibility even higher somewhere 13 line

**Comment by cossssmin** [comment]
`delimitersSettings`, which the `ignoredBefore` and `ignoredAfter` variables (which are the delimiters, `{{` and `}}` by default) use, are not set at that point in time...

**Comment by Scrum** [comment]
I mean, in line 13, initialize them so that they are accessible from any scoup

**Comment by cossssmin** [comment]
Not sure what to initialize them to or how you'd like it to work, sorry... I'd appreciate your assistance if you can, feel free to update the PR :)

**Comment by Scrum** [comment]
@cossssmin its ok ?

**Comment by Scrum** [comment]
@anikethsaha ping

File: test/fixtures/expression_ignored.html [hunk 3]
```diff
@@ -1,4 +1,4 @@
 @{{ foo }}
-<p>
-  And here's a @{{ variable }} that would be undefined.
+<p data-username="@{{ user.name }}" data-user-id="user-@{{ user.id }}">
+  Here's one @{{ variable }} and here's @{{ another }}.
```
Comment (anikethsaha) [inline test/fixtures/expression_ignored.html:3]: non-blocking suggestion !

can we have one more example here with usual expression and one ignored expression on same element and also or the same attribute?

like this may 

```html
<p data-username="@{{ user.name }}" data-user-id="user-@{{ user.id }}-{{ user.id2 }}">
  And here's a @{{ variable }} that would be undefined.	  Here's one {{ variable }} and here's @{{ another }}.
```

ignore if already exists.

**Comment by cossssmin** [comment]
> @cossssmin its ok ?

Yes, sorry, I got what you meant now... 👍

File: test/fixtures/expression_ignored.html (hunk 3 above)
Comment (cossssmin) [reply test/fixtures/expression_ignored.html:3]: Once `@{{` is encountered, the entire string/attribute value is returned as-is.

So this:

```
Here's one @{{ variable }} and here's some {{ foo }}.
```

will be output as:

```
Here's one {{ variable }} and here's some {{ foo }}.
```

So `{{ foo }}` will not be evaluated. Which come to think about it, may not be ideal, but I can't see how you'd evaluate `{{ foo }}`...?

Comment (anikethsaha) [reply test/fixtures/expression_ignored.html:3]: ummm, 

can we do like if `@{{` comes, it will ignore till first occurrence of `}}` ? WDYT ?

Comment (cossssmin) [reply test/fixtures/expression_ignored.html:3]: I wonder, maybe changing the regexes here:

https://github.com/posthtml/posthtml-expressions/blob/77aaf5696593e7cd14ea41a6505e1f2d03ae8c6e/lib/index.js#L127-L138

... to match `{{ }}` or `{{{ }}}` as long as they don't start with `@`, would be better instead? So we only match non-ignored delimiters, and then we no longer have to return 'early', so my example above should (theoretically) correctly return:

```
Here's one {{ variable }} and here's some bar.
```

(assuming `foo: 'bar'` in `locals`).

Thoughts?

Comment (anikethsaha) [reply test/fixtures/expression_ignored.html:3]: > to match `{{ }}` or `{{{ }}}` as long as they don't start with `@`, would be better instead?

yeah, I think this should work.

Comment (cossssmin) [reply test/fixtures/expression_ignored.html:3]: For example, something like:

```js
const delimitersRegexp = new RegExp(`[^@]${before}(.+?)${after}`, 'g')
```

And then, we'd replace any `@{{`` _after_ they were parsed by `placeholders`.

Comment (anikethsaha) [reply test/fixtures/expression_ignored.html:3]: `[^@]` why set ?

Comment (cossssmin) [reply test/fixtures/expression_ignored.html:3]: So you don't match any `@{{ }}`. This way, we don't even need much of the code we currently have for handling `@{{ }}` expression ignoring.

Working on an example, just need to get the regex right, as it currently matches one character before `{{`, so it returns either ` {{` (with a space) or even `-{{` (with a dash in front) in the attribute example you suggested...

Comment (cossssmin) [reply test/fixtures/expression_ignored.html:3]: Maybe you guys can help with the regex, I can't get it to _not_ match the character in front.

Given this:

```html
Here's one @{{ variable }} and here's some {{ foo }}.

<p data-username="@{{ user.name }}" data-user-id="user-@{{ user.id }}-{{ user.id2 }}"></p>
```

I need it to:

- match: `{{ foo }}`, `{{ user.id2 }}`
- not match: `@{{ variable }}`, `@{{ user.name }}`, `@{{ user.id }}`

I currently have `/[^@]{{(.+?)}}/g` but it matches ` {{ foo }}` (space char in front) and `-{{ user.id2 }}` (- in front).

Comment (anikethsaha) [reply test/fixtures/expression_ignored.html:3]: i meant we can use just `^@` without the set right ...but it would be a wrong regex as it would imply beginning char not the current seems fine 👍 

yeah, I think this your example regex will do the job

Comment (cossssmin) [reply test/fixtures/expression_ignored.html:3]: It's not quite there yet, because you end up passing ` {{ foo }}` or `-{{ user.id2 }}` to `placeholders`, which will result in a `SyntaxError`.

Comment (anikethsaha) [reply test/fixtures/expression_ignored.html:3]: let me check if I can match the regex

Comment (cossssmin) [reply test/fixtures/expression_ignored.html:3]: A negative lookbehind would work I think:

```
(?<!@){{(.+?)}}
```

And it's supported since Node 8.1.0, so I think it should work. Will test and confirm.

Comment (cossssmin) [reply test/fixtures/expression_ignored.html:3]: Got it working, will push it up in a moment 👍

Comment (anikethsaha) [reply test/fixtures/expression_ignored.html:3]: can you try `^(?! )[^@]{(.+?)}}` ?

Comment (anikethsaha) [reply test/fixtures/expression_ignored.html:3]: great 👍

Comment (cossssmin) [reply test/fixtures/expression_ignored.html:3]: So although I got it working, I think I found an issue with how `placeholders` treats unescaped delimiters. 

Basically, since it loops over every item in the `settings` object it receives, it'll still match `{{ var }}` inside `@{{{ var }}}`.

I'll push the fix for regular, escaped delimiters and will open a separate issue for unescaped delimiters.

Comment (anikethsaha) [reply test/fixtures/expression_ignored.html]: > I'll push the fix for regular, escaped delimiters and will open a separate issue for unescaped delimiters.

cool 👍

**Comment by Scrum** [comment]
@cossssmin publish v1.4.1
